"""initial schema

Revision ID: 641637972ffe
Revises: 
Create Date: 2026-03-06 18:52:15.606691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641637972ffe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('content_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_content_id'), ['content_id'], unique=True)

    op.create_table('learner_models',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('default_mastery', sa.Float(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('content_interactions', sa.JSON(), nullable=False),
    sa.Column('total_learning_time', sa.Integer(), nullable=False),
    sa.Column('topics_completed', sa.Integer(), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('elo_config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learner_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learner_models_learner_id'), ['learner_id'], unique=True)

    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('prerequisite_topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prerequisite_topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_prerequisite_topic_id'), ['prerequisite_topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topics_topic_id'), ['topic_id'], unique=True)

    op.create_table('content_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_model_id', sa.Integer(), nullable=False),
    sa.Column('content_record_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.String(length=120), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('performance_score', sa.Float(), nullable=True),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('skills_practiced', sa.JSON(), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_record_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['learner_model_id'], ['learner_models.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_interactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_interactions_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_interactions_content_record_id'), ['content_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_interactions_learner_model_id'), ['learner_model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_interactions_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_interactions_topic_id'), ['topic_id'], unique=False)

    op.create_table('content_topics',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_topics')
    with op.batch_alter_table('content_interactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_interactions_topic_id'))
        batch_op.drop_index(batch_op.f('ix_content_interactions_timestamp'))
        batch_op.drop_index(batch_op.f('ix_content_interactions_learner_model_id'))
        batch_op.drop_index(batch_op.f('ix_content_interactions_content_record_id'))
        batch_op.drop_index(batch_op.f('ix_content_interactions_content_id'))

    op.drop_table('content_interactions')
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_topic_id'))
        batch_op.drop_index(batch_op.f('ix_topics_prerequisite_topic_id'))

    op.drop_table('topics')
    with op.batch_alter_table('learner_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learner_models_learner_id'))

    op.drop_table('learner_models')
    with op.batch_alter_table('content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_content_id'))

    op.drop_table('content')
    # ### end Alembic commands ###
